name: test3 for hashcat

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "macos-latest"
    name: "Cargo"
    steps:
    - name: "Clone Hashcat"
      run: |
        git clone https://github.com/hashcat/hashcat
    - name: "Build Hashcat"
      run: |
        cd hashcat/
        make
    - name: "Run Hashcat"
      run: |
        cd hashcat/
        ls
        ./hashcat -m 13000 -a 3 "$rar5$16$89e6ff16878d66d9abdaae1fc84dbefe$15$b38b6d2b34d1cf8e2704f6d66230d54f$8$a4fb3374e437133e" ?l?l?l?l

