name: test3 for hashcat

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: "macos-latest"
    name: "Cargo"
    steps:
    - name: "Clone Hashcat"
      run: |
        brew install mingw-w64
        git clone https://github.com/hashcat/hashcat
        git clone https://github.com/win-iconv/win-iconv
        cd win-iconv/
        patch < ../hashcat/tools/win-iconv-64.diff
        sudo make install
        cd ../
    - name: "Build Hashcat"
      run: |
        cd hashcat/
        make win
    - name: "Run Hashcat"
      run: |
        cd hashcat/
        ls
        ./hashcat -m 13000 -a 3 $rar5$16$89e6ff16878d66d9abdaae1fc84dbefe$15$b38b6d2b34d1cf8e2704f6d66230d54f$8$a4fb3374e437133e ?l?l?l?l

